/**
 * Scrapbook
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EditorInteractionComment } from './editorInteractionComment';
import { EditorObjectTypeEnum } from './editorObjectTypeEnum';


export interface CommentOutput { 
    id?: string;
    objectId?: string;
    objectTypeEnum?: EditorObjectTypeEnum;
    interactionId?: string;
    message?: string | null;
    parentId?: string | null;
    userId?: string;
    children?: Array<EditorInteractionComment> | null;
}

