/**
 * Scrapbook
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EditorDocumentAllowedAccess } from './editorDocumentAllowedAccess';


export interface DocumentOutput { 
    id?: string;
    title?: string | null;
    description?: string | null;
    documentAccess?: EditorDocumentAllowedAccess;
    image?: string | null;
    userId?: string;
    creationTime?: string | null;
    lastUpdateTime?: string | null;
    pageNumber?: number;
}

