/**
 * Scrapbook
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NotificationTypeEnum } from './notificationTypeEnum';


export interface Notification { 
    userId?: string;
    message?: string | null;
    notificationType?: NotificationTypeEnum;
    wasRead?: boolean;
    linkId?: string | null;
    id?: string;
}

