export * from './contactFormServiceProxy';
import { ContactFormServiceProxy } from './contactFormServiceProxy';
export * from './documentServiceProxy';
import { DocumentServiceProxy } from './documentServiceProxy';
export * from './documentInstanceServiceProxy';
import { DocumentInstanceServiceProxy } from './documentInstanceServiceProxy';
export * from './documentTagServiceProxy';
import { DocumentTagServiceProxy } from './documentTagServiceProxy';
export * from './documentsServiceProxy';
import { DocumentsServiceProxy } from './documentsServiceProxy';
export * from './feedServiceProxy';
import { FeedServiceProxy } from './feedServiceProxy';
export * from './profileServiceProxy';
import { ProfileServiceProxy } from './profileServiceProxy';
export * from './userPreferencesServiceProxy';
import { UserPreferencesServiceProxy } from './userPreferencesServiceProxy';
export const APIS = [ContactFormServiceProxy, DocumentServiceProxy, DocumentInstanceServiceProxy, DocumentTagServiceProxy, DocumentsServiceProxy, FeedServiceProxy, ProfileServiceProxy, UserPreferencesServiceProxy];
